import { StyleSheet, Dimensions } from 'react-native';
const { width } = Dimensions.get('window');
const SCALE = Math.max(0.9, Math.min(width / 375, 1.18));
const rf = (n: number) => Math.round(n * SCALE);
export const CROSSHAIR_LENGTH_FACTOR = 0.5;
export const CROSSHAIR_LENGTH_FACTOR_FROZEN = 0.35;
export const CROSSHAIR_THICKNESS = 2;
export const CROSSHAIR_DOT_SIZE = 10;
export const CROSSHAIR_DOT_BORDER = 2;
export const CROSSHAIR_CONTAINER_SIZE = CROSSHAIR_DOT_SIZE + CROSSHAIR_DOT_BORDER * 2;
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FCF8F7' },
  header: { flexDirection: 'row', justifyContent: 'space-between', padding: rf(14) },
  backButton: { width: rf(48), height: rf(48), borderRadius: rf(24), justifyContent: 'center', alignItems: 'center', backgroundColor: '#070D0D' },
  backText: { fontSize: rf(20), fontWeight: '700', color: '#fff' },
  settingsButton: { paddingVertical: rf(8), paddingHorizontal: rf(8), borderRadius: 6, minWidth: rf(44), minHeight: rf(44), justifyContent: 'center', alignItems: 'center' },
  settingsText: { fontSize: rf(20), color: '#070D0D' },
  cameraArea: { flex: 1, justifyContent: 'flex-start', alignItems: 'center', backgroundColor: '#FCF8F7', position: 'relative', paddingTop: rf(8), paddingHorizontal: rf(12) },
  cameraPreview: { width: '100%', maxWidth: width - 32, alignSelf: 'center', aspectRatio: 4 / 3, borderRadius: 8, overflow: 'hidden', backgroundColor: '#000', position: 'relative' },
  cameraFallback: { backgroundColor: '#FCF8F7', justifyContent: 'center', alignItems: 'center', width: '100%', maxWidth: width - 32, aspectRatio: 4 / 3, borderRadius: 8 },
  cameraFallbackText: { color: '#070D0D', fontSize: rf(15) },
  permissionButton: { marginTop: rf(12), backgroundColor: '#007FFF', paddingVertical: rf(12), paddingHorizontal: rf(16), borderRadius: 10 },
  permissionButtonText: { color: '#fff', fontWeight: '700', fontSize: rf(15) },
  crosshairVertical: { position: 'absolute', width: 2, backgroundColor: '#fff', borderRadius: 0, elevation: 4 },
  crosshairHorizontal: { position: 'absolute', height: 2, backgroundColor: '#fff', borderRadius: 0, elevation: 4 },
  animatedImageAbsolute: { position: 'absolute' },
  animatedFull: { width: '100%', height: '100%' },
  selectedImage: { resizeMode: 'cover' },
  crosshairInner: { alignItems: 'center', justifyContent: 'center' },
  crosshairDotBase: { backgroundColor: 'rgba(255,0,0,0.95)' },
  crosshairLineBase: { position: 'absolute', backgroundColor: 'white' },
  cameraPreviewContainer: { width: '100%', maxWidth: width - 32, alignSelf: 'center', aspectRatio: 4 / 3, borderRadius: 8, overflow: 'hidden', backgroundColor: '#000', position: 'relative' },
  cameraInner: { width: '100%', height: '100%' },
  previewWrapper: { width: '100%', alignItems: 'center', position: 'relative' },
  debugText: { fontSize: 12, color: '#070D0D' },
  debugBlock: { marginTop: 8 },
  absoluteOverlay: { position: 'absolute', left: 0, top: 0 },
  fillerBar: { position: 'absolute', backgroundColor: '#FCF8F7' },
  crosshairContainer: { position: 'absolute', justifyContent: 'center', alignItems: 'center', left: 0, top: 0 },
  crosshairDot: { width: CROSSHAIR_DOT_SIZE, height: CROSSHAIR_DOT_SIZE, borderRadius: Math.round(CROSSHAIR_DOT_SIZE/2), backgroundColor: 'rgba(255,0,0,0.95)', borderWidth: 0, elevation: 6, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 4 },
  infoArea: { padding: 20 },
  infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  infoLabel: { fontSize: rf(15), color: '#070D0D', width: Math.min(140, rf(120)) },
  infoValue: { fontSize: rf(20), fontWeight: '700', color: '#070D0D' },
  freezeButton: { marginTop: rf(12), backgroundColor: '#FF8C2B', paddingVertical: rf(14), paddingHorizontal: rf(18), borderRadius: 10, alignItems: 'center' },
  unfreezeButton: { marginTop: rf(12), backgroundColor: '#007FFF', paddingVertical: rf(14), paddingHorizontal: rf(18), borderRadius: 10, alignItems: 'center' },
  freezeButtonText: { color: '#fff', fontWeight: '700', fontSize: rf(17) },
  backIconImage: { width: rf(20), height: rf(20), tintColor: '#fff', resizeMode: 'contain' },
  uploadRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: rf(12) },
  uploadButton: { backgroundColor: '#007FFF', paddingVertical: rf(10), paddingHorizontal: rf(14), borderRadius: 10, minWidth: rf(120) },
  uploadButtonContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  uploadIcon: { width: rf(20), height: rf(20), marginRight: rf(10), tintColor: '#fff', resizeMode: 'contain' },
  uploadButtonText: { color: '#fff', fontWeight: '700', fontSize: rf(16) },
  thumbnail: { width: rf(72), height: rf(72), borderRadius: 10, marginLeft: rf(12), borderWidth: 1, borderColor: '#EEE' },
  adjustArea: { width: '100%', alignItems: 'flex-end', marginTop: rf(8), paddingRight: rf(8), zIndex: 999999, elevation: 50 },
  adjustButton: { backgroundColor: '#FCF8F7', paddingVertical: rf(10), paddingHorizontal: rf(12), borderRadius: rf(26), elevation: 6, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.12, shadowRadius: 6 },
  adjustButtonContent: { flexDirection: 'row', alignItems: 'center' },
  adjustIcon: { width: rf(20), height: rf(20), marginRight: rf(8), tintColor: '#007FFF', resizeMode: 'contain' },
  adjustText: { color: '#007FFF', fontWeight: '700', fontSize: rf(15) },
  adjustHelp: { marginTop: rf(8), paddingHorizontal: rf(12), backgroundColor: '#FF8C2B', paddingVertical: rf(10), borderRadius: 8, alignSelf: 'stretch', zIndex: 999999, elevation: 50, position: 'relative' },
  adjustHelpText: { color: '#fff', fontSize: rf(14), textAlign: 'left', fontWeight: '600' },
  swatchContainer: { position: 'absolute', right: rf(12), top: rf(12), backgroundColor: 'rgba(252,248,247,0.97)', padding: rf(8), borderRadius: rf(8), flexDirection: 'row', alignItems: 'center', elevation: 10, borderWidth: 1, borderColor: '#DDD', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.18, shadowRadius: 6 },
  swatchBox: { width: rf(44), height: rf(44), borderRadius: rf(6), borderWidth: 1, borderColor: '#DDD', marginRight: rf(8) },
  swatchText: { fontSize: rf(13), color: '#070D0D', fontWeight: '600' },
  swatchRoot: { position: 'absolute', right: rf(12), top: rf(12), zIndex: 9999, elevation: 20 },
  inlineSwatchRow: { width: '100%', alignItems: 'flex-start', marginBottom: rf(12) },
  swatchBoxLarge: { width: rf(104), height: rf(104), borderRadius: rf(12), borderWidth: 1, borderColor: '#DDD', backgroundColor: '#999' },
  processingOverlay: { position: 'absolute', left: 0, top: 0, right: 0, bottom: 0, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.45)' },
  processingBox: { padding: rf(14), borderRadius: 10, backgroundColor: 'rgba(252,248,247,0.95)', alignItems: 'center' },
  processingText: { fontSize: rf(15), color: '#070D0D', marginTop: rf(8), fontWeight: '600' },
  tapMarkerRoot: { position: 'absolute', left: 0, top: 0, width: '100%', height: '100%', pointerEvents: 'none' },
  tapMarkerDot: { position: 'absolute', width: rf(18), height: rf(18), borderRadius: rf(9), backgroundColor: 'rgba(0,200,80,0.95)', borderWidth: 2, borderColor: '#fff', elevation: 8, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 4 },
});
