import { StyleSheet } from 'react-native';

const COLORS = {
  ink: '#070D0D',
  canvas: '#FCF8F7',
  primary: '#007FFF',
  slate: '#5C6A6A',
  border: '#E4E8EA',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.canvas,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: COLORS.primary,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#005FCC',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  backIconImage: {
    width: 18,
    height: 18,
    tintColor: COLORS.canvas,
    resizeMode: 'contain',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.canvas,
  },
  scrollView: { flex: 1 },
  contentContainer: {
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  settingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  settingTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  settingTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.ink,
  },
  settingSubtitle: {
    fontSize: 14,
    color: COLORS.slate,
    marginTop: 4,
  },
  togglePill: {
    width: 72,
    height: 32,
    borderRadius: 18,
    alignItems: 'center',
    paddingHorizontal: 8,
    justifyContent: 'space-between',
    columnGap: 6,
  },
  togglePillOnDirection: {
    flexDirection: 'row',
  },
  togglePillOffDirection: {
    flexDirection: 'row-reverse',
  },
  togglePillOn: {
    backgroundColor: COLORS.primary,
  },
  togglePillOff: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  toggleThumb: {
    width: 26,
    height: 26,
    borderRadius: 13,
    elevation: 2,
    shadowColor: '#00000033',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
  },
  toggleThumbOn: {
    backgroundColor: '#FFFFFF',
  },
  toggleThumbOff: {
    backgroundColor: COLORS.primary,
  },
  toggleText: {
    minWidth: 28,
    fontWeight: '700',
    fontSize: 12,
    textAlign: 'center',
  },
  toggleTextOn: {
    color: '#FFFFFF',
  },
  toggleTextOff: {
    color: COLORS.primary,
  },
  voiceSection: {
    marginTop: 8,
    padding: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  voiceLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.ink,
  },
  voiceHint: {
    fontSize: 14,
    color: COLORS.slate,
    marginTop: 4,
    marginBottom: 14,
  },
  voiceDropdownWrap: {
    marginTop: 4,
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F4F7F9',
    borderWidth: 1,
    borderColor: '#D2D8DB',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 14,
  },
  dropdownButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.ink,
  },
  caret: {
    color: COLORS.slate,
    fontSize: 16,
    marginLeft: 8,
  },
  dropdownMenu: {
    marginTop: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#EFF1F3',
  },
  dropdownItemText: {
    fontSize: 16,
    color: COLORS.ink,
  },
  fabContainer: {
    position: 'absolute',
    right: 16,
    bottom: 24,
    width: 64,
    height: 64,
  },
  fabSubmenu: {
    position: 'absolute',
    right: 0,
    bottom: 78,
    backgroundColor: 'transparent',
    alignItems: 'flex-end',
  },
  fabSubmenuItem: {
    backgroundColor: '#F0F4FF',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 16,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 200,
    justifyContent: 'flex-start',
    borderWidth: 1,
    borderColor: '#D8E4FF',
  },
  fabSubmenuIcon: {
    marginRight: 10,
    color: COLORS.ink,
    fontSize: 18,
  },
  fabSubmenuImageSize: {
    width: 22,
    height: 18,
    tintColor: COLORS.ink,
    resizeMode: 'contain',
  },
  fabSubmenuText: {
    fontWeight: '700',
    color: COLORS.ink,
    flexShrink: 1,
    flexWrap: 'nowrap',
  },
  fabMain: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: COLORS.ink,
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  fabMainIcon: {
    color: COLORS.canvas,
    fontSize: 26,
    fontWeight: '700',
  },
});
